export const AlertType = Object.freeze({
    CAPACITY_CRITICAL: 'CAPACITY_CRITICAL',
    CAPACITY_NEAR_LIMIT: 'CAPACITY_NEAR_LIMIT',
    STAY_EXCEEDED: 'STAY_EXCEEDED',
    UNRECOGNIZED_PLATE: 'UNRECOGNIZED_PLATE',
    ACCESS_WITHOUT_RESERVATION: 'ACCESS_WITHOUT_RESERVATION'
});
